### ISSUE TITLE
Segfault when registering command bus

### ISSUE THREAD

**Issue by szymach** [prooph/service-bus-symfony-bundle#24]
Hello,
I have tried registering your bundle like so:

```yaml
prooph_service_bus:
    command_buses:
        command_bus: ~
```

while running my app on a Symfony3 web server with PHP 7.1. This has resulted in segfaults when attemping to use the console commands. The only clue I can give is that it was related to `strtolower` function and was fixed by changing the configuration to:

```yaml
prooph_service_bus:
    command_buses:
        app_command_bus: ~ # <- a prefix
```
