### ISSUE TITLE
Document features

### ISSUE THREAD

**Issue by codeliner** [prooph/service-bus-symfony-bundle#30]
- [x] Tag handlers/listeners
- [x] Tag plugins
- [x] PsrLogger per bus
- [x] message detection
- [x] async switch
- [x] debug bar integration

**Comment by eugenegp** [comment]
@codeliner 
Any news about using in async mode? May be you have some prod code examples?

**Comment by codeliner** [comment]
@eugenegp sorry, I've missed your question: General usage of async switch router is documented here: http://docs.getprooph.org/service-bus/plugins.html#2-3-1

For symfony the config can look something like that:

```
event_buses:
    acq_event_bus:
      plugins:
        - 'prooph_service_bus.on_event_invoke_strategy'
      router:
        type: 'prooph_service_bus.event_bus_router'
        async_switch: '@acq_app.sqs_message_producer'
        routes:
          'CoopNegotiationWasCompleted':
            - 'acq_app.send_coop_negotiation_completed_mail'
```
