### ISSUE TITLE
Disable DataCollectorPlugin

### ISSUE THREAD

**Issue by enumag** [prooph/service-bus-symfony-bundle#66]
For some reason the DataCollectorPlugin slows the performance of my import by roughly 100%. According to blackfire.io the plugin greatly increases time used by garbage collector. I don't care why that happens since I don't really need the plugin.

I obviously can't set `kernel.debug` to `false` since I want to see errors. And I can't uninstall `symfony/stopwatch` either since it is required by `friendsofphp/php-cs-fixer`. So I need some other way to disable this plugin. How can I do that?

**Comment by enumag** [comment]
For now I'm using this workaround but there should be some other way in my opinion.

```yaml
services:
    prooph_service_bus.plugin.data_collector:
        class: App\Library\Prooph\Infrastructure\NullPlugin
```

```php
<?php declare(strict_types = 1);

namespace App\Library\Prooph\Infrastructure;

use Prooph\ServiceBus\MessageBus;
use Prooph\ServiceBus\Plugin\Plugin;

class NullPlugin implements Plugin
{
	public function attachToMessageBus(MessageBus $messageBus): void
	{
	}

	public function detachFromMessageBus(MessageBus $messageBus): void
	{
	}
}
```
