### ISSUE TITLE
BC Break with merged commit 8c5608b

### ISSUE THREAD

**Issue by sinansoezen** [prooph/service-bus-symfony-bundle#68]
Hey,

the changes in commit [8c5608b](https://github.com/prooph/service-bus-symfony-bundle/commit/8c5608b18fab4867644dc18ca03acb0e65e8ce0f), especially the addition in line [#110](https://github.com/prooph/service-bus-symfony-bundle/commit/8c5608b18fab4867644dc18ca03acb0e65e8ce0f#diff-58ebd0dce0407f0902c7f296773401c9R110) cause a BC break in our application. It causes the Events thrown by our ProcessManagers to be ignored.

Our ProcessManagers are declared in the following way through tags:
```yaml
App\ProcessManager\:
   resource: '../src/ProcessManager/*'
   public: true
   tags: [{ name: 'prooph_service_bus.portal_event_bus.route_target', message_detection: true }]
```

Greetings, Sinan
